# Options for analysis running.
#run:
#  # See the dedicated "run" documentation section.
#  option: value
## output configuration options
#output:
#  # See the dedicated "output" documentation section.
#  option: value
## All available settings of specific linters.

linters-settings:
  gocognit:
    # Minimal code complexity to report.
    # Default: 30 (but we recommend 10-20)
    min-complexity: 10
  revive:
    # Maximum number of open files at the same time.
    # See https://github.com/mgechev/revive#command-line-flags
    # Defaults to unlimited.
    max-open-files: 2048
    # When set to false, ignores files with "GENERATED" header, similar to golint.
    # See https://github.com/mgechev/revive#available-rules for details.
    # Default: false
    ignore-generated-header: true
    severity: warning
    enable-all-rules: false
    # Sets the default failure confidence.
    # This means that linting errors with less than 0.8 confidence will be ignored.
    # Default: 0.8
    confidence: 0.8
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#max-control-nesting
      - name: max-control-nesting
        severity: error
        disabled: false
        exclude: [""]
        arguments: [3]


linters:
  enable:
#    - revive
    - nestif
    - gocognit

#issues:
#  # See the dedicated "issues" documentation section.
#  option: value
#severity:
#  # See the dedicated "severity" documentation section.
#  option: value