name: go test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1


    steps:
      - uses: actions/checkout@v4
      ## Setup GO
      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Display Go version
        run: go version
      - name: install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y libsqlite3-0 libsqlite3-dev build-essential

      - name: go benchmark
        run: make benchmark
