name: go test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      ## Setup GO
      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Display Go version
        run: go version
      - name: install dependencies
        run: |
          apt-get update \
          apt-get install -y libsqlite3-dev

      ## Setup node
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      ## verify
      - name: build UI
        run: make package-ui
      - name: go test
        run: make test
      - name: go benchmark
        run: make benchmark

      #
#      - name: Golangci-lint
#        uses: golangci/golangci-lint-action@v6.0.1


