name: verify code

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      ## Setup GO
      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Display Go version
        run: go version
      - name: install go-licence-detectors
        run: go install go.elastic.co/go-licence-detector@latest

      ## Setup node
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      ## verify
      - name: build UI
        run: make package-ui

      - name: go test
        run: make test

      - name: go benchmark
        run: make benchmark

      - name: check licenses
        run: make license-check
      #
#      - name: Golangci-lint
#        uses: golangci/golangci-lint-action@v6.0.1


