name: verify licenses

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      ## Setup GO
      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: install go-licence-detectors
        run: go install go.elastic.co/go-licence-detector@latest

      - name: check licenses
        run: make license-check
